parameters:
  merch_data_database_url_default: 'postgresql://localhost/merchandising?serverVersion=16&charset=utf8'

doctrine:
  dbal:
    default_connection: data
    connections:
      data:
        driver: pdo_pgsql
        url: '%env(default:merch_data_database_url_default:MERCH_DATA_DATABASE_URL)%'
        server_version: '16'
      infra:
        driver: pdo_sqlite
        path: '%kernel.project_dir%/var/infra.db'
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: data
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Merchandising:
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Merchandising\Entity'
            alias: Merch
            is_bundle: false
