<?php

declare(strict_types=1);

namespace App\Merchandising\Migration;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260913165100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the initial Merchandising-owned surface, section, and placement tables.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('CREATE TABLE merch_surface (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, surface_key VARCHAR(120) NOT NULL, title VARCHAR(180) NOT NULL, surface_type VARCHAR(80) NOT NULL, status VARCHAR(40) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MERCH_SURFACE_SURFACE_KEY ON merch_surface (surface_key)');
        $this->addSql('CREATE TABLE merch_section (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, section_key VARCHAR(120) NOT NULL, title VARCHAR(180) NOT NULL, section_type VARCHAR(80) NOT NULL, priority INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE merch_placement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, placement_key VARCHAR(120) NOT NULL, source_type VARCHAR(80) NOT NULL, source_reference VARCHAR(180) DEFAULT NULL, priority INT NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('DROP TABLE merch_placement');
        $this->addSql('DROP TABLE merch_section');
        $this->addSql('DROP TABLE merch_surface');
    }
}
